name: rl
version: git
summary: rl (readline) allows users to run commands like grep interactively.
description: |
  rl (readline) allows users to run commands like grep interactively.
confinement: devmode
base: core20

apps:
  rl-source:
    command: bin/rl

parts:
  rl-source:
    source: .
    plugin: go
    go-channel: 1.15/stable
    stage-packages:
      - gcc
    build-environment:
      - CGO_ENABLED: "0"
