name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: snapcore/action-build@v1
    - run: |
        sudo snap install --dangerous ${{ steps.snapcraft.outputs.snap }}
        rl -h
