name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Snap Package
      id: snapcraft
      uses: snapcore/action-build@v1

    - name: Test Installation
      run: |
        sudo snap install --dangerous ${{ steps.snapcraft.outputs.snap }}
        rl -h
